spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/pagamentos1?createDatabaseIfNotExist=true
    username: root
    password: 4C*VU8ngvSXJe6


  jpa:
    show-sql: true